version: '3.7'

services:
  council-daemon:
    image: lidofinance/lido-council-daemon@sha256:58c54f85aeaf57f41f3250c4f1ff5da5f1b08d8a4610a9593203986c2533317e
    ports:
      - "3000:3000" # port is used for prometheus metrics
    environment:
      - "PORT=3000"
      - "LOG_LEVEL=debug"
      - "LOG_FORMAT=simple"
      - "RPC_URL=<rpc url>"
      - "KAFKA_SSL=true"
      - "KAFKA_SASL_MECHANISM=plain"
      - "KAFKA_USERNAME=<kafka user>"
      - "KAFKA_PASSWORD=<kafka password>"
      - "KAFKA_BROKER_ADDRESS_1=<kafka address>"
      - "KAFKA_TOPIC=defender"
      - "WALLET_PRIVATE_KEY"

    # volumes can be omitted if needed
    volumes:
      - ./.volumes/cache/:/council/cache/

