version: '3.7'

services:
  council-daemon:
    image: lidofinance/lido-council-daemon:1.0.0
    ports:
      - "3000:3000"
    environment:
      - "PORT=3000"
      - "LOG_LEVEL=debug"
      - "LOG_FORMAT=simple"
      - "RPC_URL=<rpc url>"
      - "KAFKA_SSL=true"
      - "KAFKA_SASL_MECHANISM=plain"
      - "KAFKA_USERNAME=<kafka user>"
      - "KAFKA_PASSWORD=<kafka password>"
      - "KAFKA_BROKER_ADDRESS_1=<kafka address>"
      - "WALLET_PRIVATE_KEY=<wallet private key>"

