version: '3.7'

services:
  council-daemon:
    image: lidofinance/lido-council-daemon@sha256:679e171405b46335500796afbace495329d28879488ae255d8cb1270e56847f4
    ports:
      - "3000:3000" # port is used for prometheus metrics
    environment:
      - "PORT=3000"
      - "LOG_LEVEL=debug"
      - "LOG_FORMAT=simple"
      - "RPC_URL=<rpc url>"
      - "KAFKA_SSL=true"
      - "KAFKA_SASL_MECHANISM=plain"
      - "KAFKA_USERNAME=<kafka user>"
      - "KAFKA_PASSWORD=<kafka password>"
      - "KAFKA_BROKER_ADDRESS_1=<kafka address>"
      - "KAFKA_TOPIC=defender"
      - "WALLET_PRIVATE_KEY"

    # volumes can be omitted if needed
    volumes:
      - ./.volumes/cache/:/council/cache/

