# This is an example
integrations:

  # Configuration parameters to be able to connect with RabbitMQ
#  alertmanager:
#    url: "https://mimir-gateway.tools.fpkmon.com"
#    headers:
#      X-Scope-OrgID: freepik-company

#  webhook:
#    url: "https://${TEST_USERNAME}:${TEST_PASSWORD}@webhook.site/98f1c771-bfaf-4c4f-81f6-f11c76684fcf"
#    headers:
#      X-Scope-OrgID: freepik-company

  alertmanager:
    url: "https://${TEST_USERNAME}:${TEST_PASSWORD}@webhook.site/d0fd5417-8931-476c-ae6e-c41eda3682af"
    headers:
      X-Scope-OrgID: freepik-company
