integrations:
  # (Optional) Configuration parameters to be able to connect with generic webhooks
  webhook:
    url: "https://${WEBHOOK_TEST_USERNAME}:${WEBHOOK_TEST_PASSWORD}@webhook.site/dffa7c58-a11f-4bc5-9ead-305fa2ac6237"
    headers:
      X-Scope-OrgID: your-company

  # (Optional) Configuration parameters to be able to connect with Alertmanager
  alertmanager:
    url: "https://${TEST_USERNAME}:${TEST_PASSWORD}@webhook.site/d0fd5417-8931-476c-ae6e-c41eda3682af"
    headers:
      X-Scope-OrgID: freepik-company
