integrations:

  # (Optional) Configuration parameters to send generic webhooks
  - name: webhook-sender
    type: webhook
    webhook:
      url: "https://${WEBHOOK_TEST_USERNAME}:${WEBHOOK_TEST_PASSWORD}@webhook.site/c95d5e66-fb9d-4d03-8df5-47f87ede84d2"
      verb: GET
      headers:
        X-Scope-OrgID: freepik-company

  # (Optional) Configuration parameters to send generic webhooks with validators
  - name: webhook-sender-with-validator
    type: webhook
    webhook:
      url: "https://${WEBHOOK_TEST_USERNAME}:${WEBHOOK_TEST_PASSWORD}@webhook.site/c95d5e66-fb9d-4d03-8df5-47f87ede84d2"
      verb: POST
      validator: alertmanager
      headers:
        X-Scope-OrgID: freepik-company

  # (Optional) Configuration parameters to send generic webhooks with validators
  - name: webhook-sender-with-validator-other
    type: webhook
    webhook:
      url: "https://${WEBHOOK_TEST_USERNAME}:${WEBHOOK_TEST_PASSWORD}@webhook.site/c95d5e66-fb9d-4d03-8df5-47f87ede84d2"
      verb: PUT
      validator: alertmanager
      headers:
        X-Scope-OrgID: freepik-company


