version: 2.1

workflows:
  workflow:
    jobs:
      - linux-test:
          matrix:
              parameters:
                  php-version: ["7.3", "7.4", "8.0", "8.1"]
                  composer-dependencies: ["lowest", "highest"]

jobs:
  linux-test:
    parameters:
      php-version:
        type: string
      composer-dependencies:
        type: string

    docker:
      - image: cimg/php:<<parameters.php-version>>
      - image: redis

    steps:
      - checkout
      - run:
          name: install dependencies
          command: composer install --no-progress
      - when:
          condition:
            equal: [ <<parameters.composer-dependencies>>, "lowest" ]
          steps:
            - run:
                name: downgrade to lowest versions
                command: composer update --prefer-lowest --prefer-stable
      - run: mkdir -p ./phpunit
      - run:
          name: run tests
          command: php vendor/bin/phpunit
      - store_test_results:
          path: ./phpunit
      - store_artifacts:
          path: ./phpunit
