# permissions for end users to edit notifications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: notification-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: jokati2
    app.kubernetes.io/part-of: jokati2
    app.kubernetes.io/managed-by: kustomize
  name: notification-editor-role
rules:
- apiGroups:
  - jokati.freepik.com
  resources:
  - notifications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jokati.freepik.com
  resources:
  - notifications/status
  verbs:
  - get
