apiVersion: jokati.freepik.com/v1alpha1
kind: Notification
metadata:
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/instance: notification-sample
    app.kubernetes.io/part-of: jokati2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: jokati2
  name: notification-sample
spec:
  # TODO(user): Add fields here
