{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "falcon-crowdstrike.fullname" . | default "ClusterIP" }}
  labels:
    {{- include "falcon-crowdstrike.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "falcon-crowdstrike.selectorLabels" . | nindent 4 }}
{{- end }}
