name: Opbeans Android Load Generator

on:
  workflow_dispatch:

jobs:
  opbeans_load_generator:
    runs-on: ubuntu-latest
    name: A job to generate Opbeans Android data
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute load generator
        env:
          SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
          SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
        run: |
          docker build --build-arg sauce_username=$SAUCE_USERNAME --build-arg sauce_access_key=$SAUCE_ACCESS_KEY -t load-generator ./load-generator
          docker run load-generator