name: Tests and checks
on: pull_request
jobs:
  test:
    name: App tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run lint
        run: yarn lint
      - name: Run tests
        run: yarn test

      - name: Create e2e docker containers
        run: docker-compose up -d

      - name: Run e2e tests
        run: yarn test:e2e

  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master

  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master

  actions:
    uses: lidofinance/linters/.github/workflows/actions.yml@master
